version: '3'

services:
  database-mysql:
    container_name: ticketing-service
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'ticket'
      TZ: Asia/Seoul

    ports:
      - '3306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

    restart: always
