
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket
    username: root
    password: test1234
    hikari:
      connection-timeout: 10000

  data:
    redis:
      host: 127.0.0.1
      port: 6379

#  flyway:
#    enabled: false